// ─── STOCK SYMBOL → COMPANY NAME MAPPING (for earnings call data lookup) ───
// Maps NSE stock symbols to the company folder names in the outputs/ directory
// Updated: 49 Nifty 50 companies, 231 quarterly analyses

export const STOCK_TO_COMPANY: Record<string, string> = {
  // Original 20
  "ADANIENT": "Adani",
  "BAJFINANCE": "Bajaj Finance",
  "BHARTIARTL": "Bharti Airtel",
  "CIPLA": "Cipla",
  "HCLTECH": "HCL Tech",
  "HDFCBANK": "HDFC",
  "ICICIBANK": "ICICI",
  "INFY": "Infosys",
  "ITC": "ITC",           // May not have data — check manifest
  "LT": "L&T",
  "RELIANCE": "Reliance",
  "SBIN": "SBI",
  "SUNPHARMA": "Sun Pharma",
  "TATAMOTORS": "Tata Motors",
  "TCS": "TCS",
  "WIPRO": "Wipro",
  "TITAN": "Titan Company",
  "ONGC": "ONGC",
  "NTPC": "NTPC",
  "POWERGRID": "Powergrid Corporation",

  // New 29 companies
  "ADANIPORTS": "Adani Ports and SEZ",
  "APOLLOHOSP": "Apollo Hospitals",
  "ASIANPAINT": "Asian Paints",
  "AXISBANK": "Axis",
  "BPCL": "BPCL",
  "BAJAJ-AUTO": "Bajaj Auto",
  "BAJAJFINSV": "Bajaj Finserv",
  "BRITANNIA": "Britannia Industries",
  "COALINDIA": "Coal India",
  "DIVISLAB": "Divi's Laboratories",
  "DRREDDY": "Dr. Reddy's Laboratories",
  "EICHERMOT": "Eicher Motors",
  "GRASIM": "Grasim Industries",
  "HDFCLIFE": "HDFC Life",
  "HINDUNILVR": "HUL",
  "HEROMOTOCO": "Hero MotoCorp",
  "HINDALCO": "Hindalco Industries",
  "INDUSINDBK": "IndusInd Bank",
  "JSWSTEEL": "JSW Steel",
  "KOTAKBANK": "Kotak Mahindra Bank",
  "LTIM": "LTIMindtree",
  "M&M": "M&M",
  "MARUTI": "Maruti Suzuki India",
  "NESTLEIND": "Nestle India",
  "SBILIFE": "SBI Life Insurance",
  "TATACONSUM": "Tata Consumer Products",
  "TATASTEEL": "Tata Steel",
  "TECHM": "Tech Mahindra",
  "UPL": "UPL Ltd",
  "ULTRACEMCO": "Ultratech Cement",
};
