import type { LegDraft, StrategyDefinition, StrategyId } from "./types"

export const STRATEGY_DEFINITIONS: Record<StrategyId, StrategyDefinition> = {
  "long-call": {
    id: "long-call",
    name: "Long Call",
    outlook: "Bullish",
    premiumProfile: "debit",
    definedRisk: true,
    profitCapped: false,
    lossCapped: true,
    description: "Educational upside exposure with loss limited to the premium paid.",
    cappedExplanation: "Loss is capped at the premium paid. Profit can increase as the underlying rises.",
    legTemplates: [{ id: "long-call", label: "Buy call", optionType: "call", side: "long" }],
  },
  "long-put": {
    id: "long-put",
    name: "Long Put",
    outlook: "Bearish",
    premiumProfile: "debit",
    definedRisk: true,
    profitCapped: true,
    lossCapped: true,
    description: "Educational downside exposure with loss limited to the premium paid.",
    cappedExplanation: "Loss is capped at the premium paid. Profit is capped because the underlying cannot fall below zero.",
    legTemplates: [{ id: "long-put", label: "Buy put", optionType: "put", side: "long" }],
  },
  "bull-call-spread": {
    id: "bull-call-spread",
    name: "Bull Call Spread",
    outlook: "Moderately bullish",
    premiumProfile: "debit",
    definedRisk: true,
    profitCapped: true,
    lossCapped: true,
    description: "Buy a lower-strike call and sell a higher-strike call with the same expiry.",
    cappedExplanation: "The short higher-strike call caps profit. The net debit caps loss.",
    legTemplates: [
      { id: "long-lower-call", label: "Buy lower call", optionType: "call", side: "long" },
      { id: "short-higher-call", label: "Sell higher call", optionType: "call", side: "short" },
    ],
  },
  "bear-put-spread": {
    id: "bear-put-spread",
    name: "Bear Put Spread",
    outlook: "Moderately bearish",
    premiumProfile: "debit",
    definedRisk: true,
    profitCapped: true,
    lossCapped: true,
    description: "Buy a higher-strike put and sell a lower-strike put with the same expiry.",
    cappedExplanation: "The short lower-strike put caps profit. The net debit caps loss.",
    legTemplates: [
      { id: "long-higher-put", label: "Buy higher put", optionType: "put", side: "long" },
      { id: "short-lower-put", label: "Sell lower put", optionType: "put", side: "short" },
    ],
  },
  "bull-put-spread": {
    id: "bull-put-spread",
    name: "Bull Put Spread",
    outlook: "Moderately bullish",
    premiumProfile: "credit",
    definedRisk: true,
    profitCapped: true,
    lossCapped: true,
    description: "Sell a higher-strike put and buy a lower-strike put with the same expiry.",
    cappedExplanation: "The net credit caps profit. The long lower-strike put caps loss.",
    legTemplates: [
      { id: "long-lower-put", label: "Buy lower put", optionType: "put", side: "long" },
      { id: "short-higher-put", label: "Sell higher put", optionType: "put", side: "short" },
    ],
  },
  "bear-call-spread": {
    id: "bear-call-spread",
    name: "Bear Call Spread",
    outlook: "Moderately bearish",
    premiumProfile: "credit",
    definedRisk: true,
    profitCapped: true,
    lossCapped: true,
    description: "Sell a lower-strike call and buy a higher-strike call with the same expiry.",
    cappedExplanation: "The net credit caps profit. The long higher-strike call caps loss.",
    legTemplates: [
      { id: "short-lower-call", label: "Sell lower call", optionType: "call", side: "short" },
      { id: "long-higher-call", label: "Buy higher call", optionType: "call", side: "long" },
    ],
  },
  "long-straddle": {
    id: "long-straddle",
    name: "Long Straddle",
    outlook: "Large move expected",
    premiumProfile: "debit",
    definedRisk: true,
    profitCapped: false,
    lossCapped: true,
    description: "Buy a call and put at the same strike and expiry.",
    cappedExplanation: "Loss is capped at total premium paid. Upside profit is uncapped; downside profit is capped at zero underlying price.",
    legTemplates: [
      { id: "long-call", label: "Buy call", optionType: "call", side: "long" },
      { id: "long-put", label: "Buy put", optionType: "put", side: "long" },
    ],
  },
  "long-strangle": {
    id: "long-strangle",
    name: "Long Strangle",
    outlook: "Large move expected",
    premiumProfile: "debit",
    definedRisk: true,
    profitCapped: false,
    lossCapped: true,
    description: "Buy an out-of-the-money put and call with the same expiry.",
    cappedExplanation: "Loss is capped at total premium paid. Upside profit is uncapped; downside profit is capped at zero underlying price.",
    legTemplates: [
      { id: "long-lower-put", label: "Buy lower put", optionType: "put", side: "long" },
      { id: "long-higher-call", label: "Buy higher call", optionType: "call", side: "long" },
    ],
  },
  "iron-condor": {
    id: "iron-condor",
    name: "Iron Condor",
    outlook: "Range-bound",
    premiumProfile: "credit",
    definedRisk: true,
    profitCapped: true,
    lossCapped: true,
    description: "Defined-risk range strategy using a put spread and a call spread with one expiry.",
    cappedExplanation: "The net credit caps profit. Long outside wings cap loss.",
    legTemplates: [
      { id: "long-lower-put", label: "Buy lower put", optionType: "put", side: "long" },
      { id: "short-higher-put", label: "Sell higher put", optionType: "put", side: "short" },
      { id: "short-lower-call", label: "Sell lower call", optionType: "call", side: "short" },
      { id: "long-higher-call", label: "Buy higher call", optionType: "call", side: "long" },
    ],
  },
  "iron-butterfly": {
    id: "iron-butterfly",
    name: "Iron Butterfly",
    outlook: "Range-bound",
    premiumProfile: "credit",
    definedRisk: true,
    profitCapped: true,
    lossCapped: true,
    description: "Sell an at-the-money call and put, protected by lower and higher wings.",
    cappedExplanation: "The net credit caps profit. Long outside wings cap loss.",
    legTemplates: [
      { id: "long-lower-put", label: "Buy lower put", optionType: "put", side: "long" },
      { id: "short-middle-put", label: "Sell middle put", optionType: "put", side: "short" },
      { id: "short-middle-call", label: "Sell middle call", optionType: "call", side: "short" },
      { id: "long-higher-call", label: "Buy higher call", optionType: "call", side: "long" },
    ],
  },
}

export const STRATEGY_IDS = Object.keys(STRATEGY_DEFINITIONS) as StrategyId[]

export function createLegDrafts(strategyId: StrategyId): LegDraft[] {
  return STRATEGY_DEFINITIONS[strategyId].legTemplates.map((template) => ({
    ...template,
    strike: "",
    premium: "",
    quantity: "1",
    lotSize: "",
  }))
}
