export const nifty50Stocks = [
  { symbol: "RELIANCE", name: "Reliance Industries", price: 2456.75, change: 1.23, sector: "Energy" },
  { symbol: "TCS", name: "Tata Consultancy Services", price: 3892.40, change: -0.45, sector: "IT" },
  { symbol: "HDFCBANK", name: "HDFC Bank", price: 1678.90, change: 0.87, sector: "Banking" },
  { symbol: "INFY", name: "Infosys", price: 1534.25, change: -1.12, sector: "IT" },
  { symbol: "ICICIBANK", name: "ICICI Bank", price: 1023.50, change: 2.34, sector: "Banking" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever", price: 2567.80, change: 0.56, sector: "FMCG" },
  { symbol: "ITC", name: "ITC Limited", price: 456.35, change: 1.78, sector: "FMCG" },
  { symbol: "SBIN", name: "State Bank of India", price: 634.20, change: -0.23, sector: "Banking" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel", price: 1245.60, change: 1.45, sector: "Telecom" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank", price: 1789.30, change: -0.67, sector: "Banking" },
  { symbol: "LT", name: "Larsen & Toubro", price: 3456.70, change: 0.98, sector: "Infrastructure" },
  { symbol: "AXISBANK", name: "Axis Bank", price: 1098.45, change: 1.56, sector: "Banking" },
  { symbol: "ASIANPAINT", name: "Asian Paints", price: 2876.90, change: -0.34, sector: "Consumer Goods" },
  { symbol: "MARUTI", name: "Maruti Suzuki", price: 10234.50, change: 2.12, sector: "Automobile" },
  { symbol: "HCLTECH", name: "HCL Technologies", price: 1456.80, change: -0.89, sector: "IT" },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical", price: 1123.45, change: 1.34, sector: "Pharma" },
  { symbol: "TITAN", name: "Titan Company", price: 3234.60, change: 0.78, sector: "Consumer Goods" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance", price: 6789.25, change: -1.45, sector: "Finance" },
  { symbol: "WIPRO", name: "Wipro", price: 456.70, change: 0.23, sector: "IT" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement", price: 8765.40, change: 1.67, sector: "Cement" },
  { symbol: "ONGC", name: "Oil & Natural Gas Corp", price: 234.56, change: -0.56, sector: "Energy" },
  { symbol: "NTPC", name: "NTPC Limited", price: 345.80, change: 2.45, sector: "Power" },
  { symbol: "POWERGRID", name: "Power Grid Corp", price: 267.90, change: 1.23, sector: "Power" },
  { symbol: "M&M", name: "Mahindra & Mahindra", price: 1567.80, change: 0.45, sector: "Automobile" },
  { symbol: "TATAMOTORS", name: "Tata Motors", price: 678.90, change: -2.34, sector: "Automobile" },
  { symbol: "JSWSTEEL", name: "JSW Steel", price: 789.45, change: 1.89, sector: "Metals" },
  { symbol: "TATASTEEL", name: "Tata Steel", price: 134.56, change: -0.78, sector: "Metals" },
  { symbol: "ADANIENT", name: "Adani Enterprises", price: 2345.70, change: 3.45, sector: "Conglomerate" },
  { symbol: "ADANIPORTS", name: "Adani Ports", price: 1234.50, change: 1.12, sector: "Infrastructure" },
  { symbol: "COALINDIA", name: "Coal India", price: 423.80, change: 0.67, sector: "Mining" },
  { symbol: "BPCL", name: "Bharat Petroleum", price: 567.90, change: -1.23, sector: "Energy" },
  { symbol: "GRASIM", name: "Grasim Industries", price: 2123.45, change: 0.89, sector: "Cement" },
  { symbol: "DRREDDY", name: "Dr. Reddy's Labs", price: 5678.90, change: 1.56, sector: "Pharma" },
  { symbol: "CIPLA", name: "Cipla", price: 1234.70, change: -0.45, sector: "Pharma" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals", price: 5890.30, change: 2.34, sector: "Healthcare" },
  { symbol: "EICHERMOT", name: "Eicher Motors", price: 3456.80, change: 0.12, sector: "Automobile" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv", price: 1567.40, change: -0.89, sector: "Finance" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto", price: 8234.50, change: 1.78, sector: "Automobile" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp", price: 4123.60, change: 0.56, sector: "Automobile" },
  { symbol: "TECHM", name: "Tech Mahindra", price: 1234.90, change: -1.34, sector: "IT" },
  { symbol: "HINDALCO", name: "Hindalco Industries", price: 523.45, change: 2.12, sector: "Metals" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank", price: 1456.70, change: -0.67, sector: "Banking" },
  { symbol: "SBILIFE", name: "SBI Life Insurance", price: 1345.80, change: 0.34, sector: "Insurance" },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance", price: 623.40, change: 1.45, sector: "Insurance" },
  { symbol: "DIVISLAB", name: "Divi's Laboratories", price: 3567.80, change: -0.23, sector: "Pharma" },
  { symbol: "BRITANNIA", name: "Britannia Industries", price: 4890.60, change: 0.78, sector: "FMCG" },
  { symbol: "NESTLEIND", name: "Nestle India", price: 23456.70, change: 1.12, sector: "FMCG" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products", price: 1023.45, change: -0.56, sector: "FMCG" },
  { symbol: "LTI", name: "LTIMindtree", price: 5234.80, change: 2.67, sector: "IT" },
  { symbol: "SHREECEM", name: "Shree Cement", price: 26789.30, change: 0.45, sector: "Cement" },
]

export type Stock = typeof nifty50Stocks[number]

export function getStockBySymbol(symbol: string): Stock | undefined {
  return nifty50Stocks.find(
    (stock) => stock.symbol.toLowerCase() === symbol.toLowerCase()
  )
}
